spring.application.name=013_springbootjwt

#Port Number
server.port = 8081

#MYSQL Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/fsad
spring.datasource.username=root
spring.datasource.password=urmi@1292

#JPA 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#EMAIL Configuration
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = drkpn.in@gmail.com
spring.mail.password = hqwo tubo iyfo khoa
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true